on:
  push:
    branches:
      - master
      - dev

name: Deploy to AWS

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAXHVYGZ73JKMBN3HK
        aws-secret-access-key: 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
        aws-region: ap-southeast-1

    - name: Setup node
      uses: actions/setup-node@v2.1.4
      with:
        node-version: 14.x

    - name: Deploy DEV
      if: ${{github.ref == 'refs/heads/dev'}}
      run: yarn && yarn deploy:dev

    - name: Clear cache DEV
      if: ${{github.ref == 'refs/heads/dev'}}
      run: aws cloudfront create-invalidation --distribution-id E2CLXUT9LP4FVK --paths /index.html
      
    - name: Deploy PROD
      if: ${{github.ref == 'refs/heads/master'}}
      run: yarn && yarn deploy:prod

    - name: Clear cache PROD
      if: ${{github.ref == 'refs/heads/master'}}
      run: aws cloudfront create-invalidation --distribution-id EG2U1Y6ZA1SS3 --paths /index.html